### ISSUE TITLE
Render video windows forms

### ISSUE THREAD

**Issue by mavbcn** [opentok/opentok-windows-sdk-samples#32]
Hi,
How can we render video in windows forms? I see all the samples are with WPF
thanks

**Comment by MichaelJolley** [comment]
@slorello89 have you tried this at all?

**Comment by v-kpheng** [comment]
Apologies for the belated reply.  Yes, @mavbcn, that *should* be possible and we'll work on this.

cc'ing @sergioturgil-vonage, in case I'm mistaken.

**Comment by sergioturgil-vonage** [comment]
Hi. Yes it's possible. I'm sorry we have no sample yet in the repo. I'll try to add more and better samples for windows during Q4. For now you can check the test app we use:

https://github.com/opentok/native-sdk-src/tree/develop/project/windows/OpenTok/test-app/OpenTokWinFormsSample

Of course since the only difference is the VideoRenderer and the dispatcher this can also be provided by customer themselves if thy prefer.
Bye!

**Comment by v-kpheng** [comment]
Thanks, @sergioturgil-vonage 🙏 

I'll add this to our backlog: https://jira.vonage.com/browse/OPENTOK-49645.

**Comment by sergioturgil-vonage** [comment]
I've uploaded a very simple BasicVideoChat app that uses winforms and version 2.24.0
Also made some small changes to the regular WPF BasicVideoChat including the version upgrad, removing x86 support (as it's no longer provided) and removing some deprecated calls.

**Comment by v-kpheng** [comment]
Awesome!  Thanks, @sergioturgil-vonage!

Closing.
