### ISSUE TITLE
Voice detection

### ISSUE THREAD

**Issue by wesoos** [opentok/opentok-windows-sdk-samples#50]
Hello, is it possible to detect that there has been no voice speaking for "x" amount of time?

**Comment by sergioturgil-vonage** [comment]
> Hello, is it possible to detect that there has been no voice speaking for "x" amount of time?

Yes with some coding. Also, the way depends on whether you mean for subscribers or for the publisher.

For subscribers it's much easier. You just need to subscribe to the AudioData event. This event is raised every 10ms and contains a batch of audio samples (samples are 2-byte signed integers). You would need to check that all samples are close enough to zero (some fine tuning would be needed to find out what is close enough to ignore a certain level of background noise).

For the publisher it's a bit more complicated since we do not provide that event. In that case you would need to provide a custom audio device. In the capturer subsystem, inside the callback to write captured samples to webrtc, you would do the same operation explained before.

There's also a second better alternative for the publisher which is not available yet but will be very soon. That is using insertable streams API (or media processing API if you prefer). This API allows configuring a IAudioTransformer with a transform callback that will be called for each batch of samples passed to webrtc (from a custom audio device or from the default audio module, it doesn't matter).
Normally you would use this to perform some transformations, like noise cancellation and such, but you can also use it to make the calculations we explained before.

**Comment by rktalusani** [comment]
they can also use this right? - https://tokbox.com/developer/sdks/windows/reference/class_open_tok_1_1_publisher.html#ac0388cd417ccd21b50764898397b0b9e

**Comment by wesoos** [comment]
Are you guys referring to the AudioStatsUpdated event?

**Comment by sergioturgil-vonage** [comment]
No, there's an AudioLevel event both for publisher and subscriber. You can subscribe to it and I believe it's raised periodically with a float that indicates the audio level at that moment.
It's a much simpler solution than what I proposed.
I don't know why I didn't think of it first.

**Comment by wesoos** [comment]
So AudioLevel is not the level of the MIC or speaker?

**Comment by sergioturgil-vonage** [comment]
It's the level of audio measured in the publissher or subscriber audio stream.

It's not really the level of audio captured from the mic or rendered in the speaker but I believe that for most applications it will suffice, right?

If not, let me know your exact use case and we can think of a solution.

**Comment by wesoos** [comment]
Thanks.  Essentially we want to detect if a participant is still on the call so we can end the call if they “forgot” to hangup, if that makes sense.

I was also thinking to use the AudioNetworkStats and look at the BytesSent property…

**Comment by sergioturgil-vonage** [comment]
No, without compression the bytes sent remain the same, even if all of them represent samples of 0 amplitude.

I imagine you're talking about a participant that is still in the call (haven't invoked unpublish/disconnect on their side) but they are not talking at all and haven't talked for a while.

In that case I would check that the subscriber.AudioLevel event has reported 0 (or close to 0) for X time.
Since this is a very easy to implement solution so I would try this first and see if it works for you.

Have in mind that this will also be true for any participant that is currently in silence or has switched of the microphone because they're just listening.

**Comment by wesoos** [comment]
Hello, quick question on this again, will this work if there is background noise?  Wind blowing or cars driving by, etc...?
Also, if I dispose a session from the c# client, will it end the entire session on the other side as well?  The reason for this whole exercise is that some clients are keeping their side open and not closing out, running the participant minutes through the roof...
